{{- if .Values.gitlab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-saml-secret
type: Opaque
stringData:
  provider: |
    name: 'saml'
    label: 'Calavera Auth'
    args:
      assertion_consumer_service_url: 'https://{{ .Values.keycloak.clients.gitlab.saml.host }}/users/auth/saml/callback'
      idp_cert_fingerprint: '{{ .Values.keycloak.clients.gitlab.saml.fingerprint }}'
      idp_sso_target_url: 'https://{{ .Values.keycloak.domain }}/auth/realms/calavera/protocol/saml/clients/{{ .Values.keycloak.clients.gitlab.saml.id }}'
      issuer: '{{ .Values.keycloak.clients.gitlab.saml.id }}'
      attribute_statements:
        first_name: ['first_name']
        last_name: ['last_name']
        name: ['name']
        username: ['name']
        email: ['email']
      name_identifier_format: 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'
{{- end }}