apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sidecar
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
 name: {{ .Release.Name }}-sidecar
rules:
  - apiGroups: ['', 'apps']
    resources: ['deployments', 'deployments/scale']
    verbs: ['update', 'list', 'get', 'patch']
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['list', 'get']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-sidecar
roleRef:
  kind: Role
  name: {{ .Release.Name }}-sidecar
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sidecar