{{- if .Values.nexus.enabled  }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-nexus
spec:
  entryPoints:
    - {{ .Values.nexus.entrypoints.https }}
  routes:
  - match: Host(`{{ .Values.nexus.domain }}`)
    kind: Rule
    services:
    - name: {{ .Values.nexus.service }}
      port: 8080
      scheme: http
  tls:
    certResolver: {{ .Values.nexus.certResolver }}
{{- end }}