{{- if .Values.openproject.enabled  }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-openproject
spec:
  entryPoints:
    - {{ .Values.openproject.entrypoints.https }}
  routes:
  - match: Host(`{{ .Values.openproject.domain }}`)
    kind: Rule
    services:
    - name: {{ .Values.openproject.service }}
      port: 80
      scheme: http
  tls:
    certResolver: {{ .Values.openproject.certResolver }}
{{- end }}