apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-api
spec:
  entryPoints:
    - {{ .Values.api.entrypoints.https }}
  routes:
  - match: Host(`{{ .Values.api.domain }}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-api
      port: 80
      scheme: http
  tls:
    certResolver: {{ .Values.api.certResolver }}